### ISSUE TITLE
ng serve failing

### ISSUE THREAD

**Issue by zvesp** [hvekriya/angular-quiz-app#1]
This issue affects [the current `master` branch](https://github.com/hvekriya/angular-quiz-app/tree/12b7f93963677b75e68da445e29d5a13ec3e5337).

## Steps to reproduce

Run
```bash
ng serve
```

## Expected behaviour

The app will be served locally for development.

## Actual behaviour

```bash
ERROR in src/app/app.component.ts(26,23): error TS2339: Property 'questions' does not exist on type '{}'.
```

**Comment by hvekriya** [comment]
@zvesp This issue has been fixed with replacing promises with observers. Thanks 👍
